---
version: '2'
services:
  data-rest-test:
    build:
      context: ./mytiles-data/data-rest-test
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    links:
      - "redis:redis"
    depends_on:
      - redis
#  service-reservation:
#    build:
#      context: ./mytiles-service/service-reservation
#      dockerfile: Dockerfile
#    ports:
#      - "9080:9080"
#    links:
#      - "redis:redis"
#    depends_on:
#      - redis
#  service-journal:
#    build:
#      context: ./mytiles-service/service-journal
#      dockerfile: Dockerfile
#    ports:
#      - "9081:9081"
#    links:
#      - "redis:redis"
#    depends_on:
#      - redis
#  service-approval:
#    build:
#      context: ./mytiles-service/service-approval
#      dockerfile: Dockerfile
#    ports:
#      - "9082:9082"
#    links:
#      - "redis:redis"
#    depends_on:
#      - redis
#  service-error:
#    build:
#      context: ./mytiles-service/service-error
#      dockerfile: Dockerfile
#    ports:
#      - "9083:9083"
#    links:
#      - "redis:redis"
#    depends_on:
#      - redis
#  webapp:
#    build:
#      context: ./mytiles-webapp
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    links:
#      - "redis:redis"
#    depends_on:
#      - redis
#      - service-reservation    
  redis:
    image: redis
    ports:
      - "6379:6379"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    volumes:
      - ./mytiles-service/redis.conf:/usr/local/etc/redis/redis.conf
      # NOTE: The following will need to change most likely to a data container
      - /data/mytiles:/mnt/mytiles:rw
