##################################################################################################
# Persistence Data Volumes
##################################################################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mytiles-persistent-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---